export enum StyleFiltersEnum {
  BASIC = 'basic',
  PARTY_DRESS = 'party-dress',
  BOHEMIAN = 'bohemian',
  PREPPY = 'preppy',
  CAREER = 'career',
  RESORT = 'resort',
  CASUAL = 'casual',
  RETRO = 'retro',
  CHIC = 'chic',
  ROCKER = 'rocker',
  CLUB_NIGHT_LIFE = 'club-night-life',
  SPORTY = 'sporty',
  ETHNIC = 'ethnic',
  STREET_STYLE = 'street-style',
  FORMAL = 'formal',
  VINTAGE = 'vintage',
  MINIMAL = 'minimal',
  MODERN = 'modern',
  WESTERN = 'western',
}

export enum ColorsFiltersEnum {
  Black = 'black',
  Purple = 'purple',
  Blue = 'blue',
  Brown = 'brown',
  Green = 'green',
  Red = 'red',
  Pink = 'pink',
  Orange = 'orange',
  Silver = 'silver',
  Yellow = 'yellow',
  Grey = 'grey',
  Beige = 'beige',
  Metallic = 'metallic',
  White = 'white',
}

export enum PatternsFilterEnum {
  AnimalPrint = 'animal-print',
  Argyle = 'argyle',
  Burnout = 'burnout',
  Camo = 'camo',
  Checker = 'checker',
  Chevron = 'chevron',
  Chiffon = 'chiffon',
  ColorBlock = 'color-block',
  Crochet = 'crochet',
  Cross = 'cross',
  Crystal = 'crystal',
  Damask = 'damask',
  Embroidered = 'embroidered',
  Floral = 'floral',
  GeometricPrint = 'geometric-print',
  Gingham = 'gingham',
  Houndstooth = 'houndstooth',
  Jaquard = 'jaquard',
  Paisley = 'paisley',
  Plaid = 'plaid',
  PolkaDot = 'polka-dot',
  PrintGraphic = 'print-graphic',
  Ruffled = 'ruffled',
  Sequined = 'sequined',
  Solid = 'solid',
  Stripe = 'stripe',
  TieDye = 'tie-dye',
  TribalAztecPrint = 'tribalaztecprint',
}

export enum SleevesFilterEnum {
  ONE_HALF_SLEEVE = '12-sleeve',
  THREE_QUARTER_SLEEVE = '34-sleeve',
  LONG_SLEEVE = 'long',
  OFF_SHOULDER = 'off-shoulder',
  SHORT_SLEEVE = 'short',
  SLEEVELESS = 'sleeveless',
  STRAPLESS = 'strapless',
}
