export enum StyleFiltersEnum {
  BASIC = 'Basic',
  PARTY_DRESS = 'partyDress',
  BOHEMIAN = 'Bohemian',
  PREPPY = 'Preppy',
  CAREER = 'Career',
  RESORT = 'Resort',
  CASUAL = 'Casual',
  RETRO = 'Retro',
  CHIC = 'Chic',
  ROCKER = 'Rocker',
  CLUB_NIGHT_LIFE = 'Club & Night Life',
  SPORTY = 'Sporty',
  ETHNIC = 'Ethnic',
  STREET_STYLE = 'Street Style',
  FORMAL = 'Formal',
  VINTAGE = 'Vintage',
  MINIMAL = 'Minimal',
  MODERN = 'Modern',
  WESTERN = 'Western',
}

export enum ColorsFiltersEnum {
  Black = 'black',
  Purple = 'purple',
  Blue = 'blue',
  Brown = 'brown',
  Green = 'green',
  Red = 'red',
  Pink = 'pink',
  Orange = 'orange',
  Silver = 'silver',
  Yellow = 'yellow',
  Grey = 'grey',
  Beige = 'beige',
  Metallic = 'metallic',
  White = 'white',
}

export enum PatternsFilterEnum {
  AnimalPrint = 'Animal Print',
  Argyle = 'Argyle',
  Burnout = 'Burnout',
  Camo = 'Camo',
  Checker = 'Checker',
  Chevron = 'Chevron',
  Chiffon = 'Chiffon',
  ColorBlock = 'Color Block',
  Crochet = 'Crochet',
  Cross = 'Cross',
  Crystal = 'Crystal',
  Damask = 'Damask',
  Embroidered = 'Embroidered',
  Floral = 'Floral',
  GeometricPrint = 'Geometric Print',
  Gingham = 'Gingham',
  Houndstooth = 'Houndstooth',
  Jaquard = 'Jaquard',
  Paisley = 'Paisley',
  Plaid = 'Plaid',
  PolkaDot = 'Polka Dot',
  PrintGraphic = 'Print / Graphic',
  Ruffled = 'Ruffled',
  Sequined = 'Sequined',
  Solid = 'Solid',
  Stripe = 'Stripe',
  TieDye = 'Tie-Dye',
  TribalAztecPrint = 'Tribal/Aztec Print',
}

export enum SleevesFilterEnum {
  ONE_HALF_SLEEVE = '1/2 Sleeve',
  THREE_QUARTER_SLEEVE = '3/4 Sleeve',
  LONG_SLEEVE = 'Long',
  OFF_SHOULDER = 'Off Shoulder',
  SHORT_SLEEVE = 'Short',
  SLEEVELESS = 'Sleeveless',
  STRAPLESS = 'Strapless',
}
